import { Dispatch, SetStateAction, useState } from "react";
import { Plus, Trash2, Table2, Layers } from "lucide-react";
import { Button } from "../ui/button";
import {
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "../ui/dialog";
import { toast } from "sonner";
import { Label } from "../ui/label";
import { Input } from "../ui/input";
import { useCreateTable } from "@/hooks/queries";

interface ColumnDefinition {
  name: string;
  type: string;
}

export default function CreateTableSchema({
  db_name,
  openChange,
  setOpenChange,
}: {
  db_name: string;
  openChange: boolean;
  setOpenChange: Dispatch<SetStateAction<boolean>>;
}) {
  const { mutate: createTable, isPending } = useCreateTable();
  const [tableName, setTableName] = useState("");
  const [columns, setColumns] = useState<ColumnDefinition[]>([{ name: "", type: "TEXT" }]);

  const handleAddColumn = () => {
    setColumns([...columns, { name: "", type: "TEXT" }]);
  };

  const handleRemoveColumn = (index: number) => {
    if (columns.length <= 1) return;

    const newColumns = [...columns];
    newColumns.splice(index, 1);
    setColumns(newColumns);
  };

  const handleColumnChange = (index: number, field: "name" | "type", value: string) => {
    const newColumns = [...columns];
    newColumns[index][field] = value;
    setColumns(newColumns);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    const trimmedTableName = tableName.trim();
    if (!trimmedTableName) {
      toast.error("Table name is required");
      return;
    }

    if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(trimmedTableName)) {
      toast.error(
        "Table name must contain only letters, numbers, and underscores (cannot start with a number)"
      );
      return;
    }

    const validColumns = columns.filter((col) => col.name.trim() !== "");

    if (validColumns.length === 0) {
      toast.error("At least one custom column is required");
      return;
    }

    // Check for reserved column names
    const hasReservedId = validColumns.some((col) => col.name.trim().toLowerCase() === "id");
    if (hasReservedId) {
      toast.error("Column 'id' is reserved for primary key and auto-generated by Nebula.");
      return;
    }

    const hasReservedCreatedAt = validColumns.some(
      (col) => col.name.trim().toLowerCase() === "created_at"
    );
    if (hasReservedCreatedAt) {
      toast.error("Column 'created_at' is reserved and auto-generated by Nebula.");
      return;
    }

    // Check for duplicate column names
    const namesSet = new Set<string>();
    for (const col of validColumns) {
      const lower = col.name.trim().toLowerCase();
      if (namesSet.has(lower)) {
        toast.error(`Duplicate column name '${col.name.trim()}'.`);
        return;
      }
      namesSet.add(lower);
    }

    createTable(
      {
        dbName: db_name,
        tableName: trimmedTableName,
        schema: validColumns.map((c) => ({
          name: c.name.trim(),
          type: c.type,
        })),
      },
      {
        onSuccess: () => {
          setTableName("");
          setColumns([{ name: "", type: "TEXT" }]);
          setOpenChange(false);
        },
      }
    );
  };

  return (
    <Dialog open={openChange} onOpenChange={setOpenChange}>
      <DialogTrigger asChild>
        <Button className="h-9 px-3.5 rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white font-medium shadow-md shadow-purple-500/20 hover:shadow-lg hover:shadow-purple-500/25 transition-all text-xs">
          <Plus className="h-4 w-4 mr-1.5" /> Add Table
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-lg rounded-2xl border border-purple-200/50 dark:border-white/10 bg-white/95 dark:bg-[#0e0d15]/95 backdrop-blur-2xl shadow-2xl p-6">
        <DialogHeader>
          <div className="flex items-center gap-2.5 mb-1">
            <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-purple-500/10 text-purple-600 dark:text-purple-400 border border-purple-500/20">
              <Table2 className="h-4 w-4" />
            </div>
            <DialogTitle className="text-lg font-bold text-gray-900 dark:text-white">
              Create Table Schema
            </DialogTitle>
          </div>
          <DialogDescription className="text-xs text-gray-500 dark:text-zinc-400">
            Define a new table schema for project{" "}
            <span className="font-mono text-purple-600 dark:text-purple-400 font-medium">
              {db_name}
            </span>
            .
          </DialogDescription>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4 pt-2">
          <div className="space-y-1.5">
            <Label
              htmlFor="tableName"
              className="text-xs font-medium text-gray-700 dark:text-zinc-300"
            >
              Table Name
            </Label>
            <Input
              id="tableName"
              value={tableName}
              onChange={(e) => setTableName(e.target.value)}
              placeholder="e.g. users, products, orders"
              autoComplete="off"
              disabled={isPending}
              className="h-9 rounded-xl border-purple-200/50 dark:border-white/10 bg-white/60 dark:bg-black/30 font-mono text-xs focus:ring-purple-500"
            />
          </div>

          {/* Auto-included system columns info */}
          <div className="flex items-center gap-2 px-3 py-2 rounded-xl bg-purple-500/5 dark:bg-purple-500/10 border border-purple-200/40 dark:border-purple-500/20 text-xs text-purple-700 dark:text-purple-300">
            <span className="font-semibold text-[11px]">Auto-included:</span>
            <div className="flex items-center gap-1.5 font-mono text-[11px]">
              <span className="px-1.5 py-0.5 rounded-md bg-purple-500/10 dark:bg-white/10 font-medium">
                id (INTEGER PK)
              </span>
              <span className="text-gray-400 dark:text-zinc-500">•</span>
              <span className="px-1.5 py-0.5 rounded-md bg-purple-500/10 dark:bg-white/10 font-medium">
                created_at (TIMESTAMP)
              </span>
            </div>
          </div>

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label className="text-xs font-medium text-gray-700 dark:text-zinc-300">
                Custom Columns & Types
              </Label>
              <span className="text-[11px] text-gray-400 font-mono">
                {columns.length} {columns.length === 1 ? "column" : "columns"}
              </span>
            </div>

            <div className="space-y-2 max-h-56 overflow-y-auto pr-1">
              {columns.map((column, index) => (
                <div
                  key={index}
                  className="flex items-center gap-2 p-1.5 rounded-xl border border-purple-200/40 dark:border-white/[0.06] bg-purple-500/[0.02] dark:bg-white/[0.02]"
                >
                  <Input
                    value={column.name}
                    onChange={(e) => handleColumnChange(index, "name", e.target.value)}
                    placeholder="e.g. name, email, price"
                    className="flex-1 h-8 rounded-lg border-purple-200/50 dark:border-white/10 bg-white/60 dark:bg-black/30 font-mono text-xs"
                  />
                  <select
                    value={column.type}
                    onChange={(e) => handleColumnChange(index, "type", e.target.value)}
                    className="h-8 rounded-lg border border-purple-200/50 dark:border-white/10 bg-white/60 dark:bg-black/30 px-2.5 py-1 text-xs font-mono text-gray-800 dark:text-zinc-200 focus:outline-hidden focus:ring-1 focus:ring-purple-500"
                  >
                    <option value="TEXT">TEXT</option>
                    <option value="INTEGER">INTEGER</option>
                    <option value="BOOLEAN">BOOLEAN</option>
                    <option value="DECIMAL">DECIMAL</option>
                    <option value="UUID">UUID</option>
                    <option value="TIMESTAMP">TIMESTAMP</option>
                    <option value="BLOB">BLOB</option>
                    <option value="REAL">REAL</option>
                  </select>
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    className="h-8 w-8 rounded-lg text-gray-400 hover:text-red-500 hover:bg-red-500/10 shrink-0"
                    onClick={() => handleRemoveColumn(index)}
                    disabled={columns.length <= 1 || isPending}
                  >
                    <Trash2 className="h-3.5 w-3.5" />
                  </Button>
                </div>
              ))}
            </div>

            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={handleAddColumn}
              className="w-full h-8 rounded-xl border-dashed border-purple-300/60 dark:border-white/15 text-xs text-purple-600 dark:text-purple-400 hover:bg-purple-500/10 dark:hover:bg-white/5 font-medium"
              disabled={isPending}
            >
              <Plus className="mr-1.5 h-3.5 w-3.5" />
              Add Column
            </Button>
          </div>

          <DialogFooter className="pt-2 gap-2">
            <Button
              type="button"
              variant="outline"
              onClick={() => setOpenChange(false)}
              disabled={isPending}
              className="rounded-xl h-9 px-4 text-xs border-purple-200/50 dark:border-white/10 hover:bg-purple-500/10 dark:hover:bg-white/5"
            >
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={isPending}
              className="rounded-xl h-9 px-4 text-xs font-medium bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white shadow-md shadow-purple-500/20"
            >
              {isPending ? "Creating..." : "Create Table"}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
